version: '3.7'

services:
  studio-backend:
    container_name: studio-backend
    build: .
    init: true
    volumes:
      - ./app.js:/app/app.js
      - ./public:/app/public
      - ./routes:/app/routes
      - ./views:/app/views
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      PORT:
      EMAIL_PASS:
      CLOUDFLARE_SITE_KEY:
      CLOUDFLARE_SECRET_KEY:
    healthcheck:
      test: node healthcheck
    logging:
      options:
        max-file: '5'
        max-size: '5m'
