version: '3.7'

services:
  studio-backend:
    container_name: studio-backend
    image: agency/studio-backend
    build: .
    volumes:
      - ./app.js:/app/app.js
      - ./public:/app/public
      - ./routes:/app/routes
      - ./views:/app/views
    ports:
      - 3001:3001
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT:
      EMAIL_PASS:
      CLOUDFLARE_SITE_KEY:
      CLOUDFLARE_SECRET_KEY:
    logging:
      options:
        max-file: '5'
        max-size: '5m'
    healthcheck:
      test: node healthcheck
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500M'
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - agency

networks:
  agency:
    name: agency
