#!/bin/bash

export APOS_RELEASE_ID=`cat /dev/urandom |env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1`
echo $APOS_RELEASE_ID > ./release-id
NODE_ENV=production node app @apostrophecms/asset:build

echo "Pre-deploy scripts ok"
