#!/bin/bash

make prod
docker restart custom-nginx # enable nginx to see new uploads

PROJECT=studio
DIR=/opt/stagecoach/apps/$PROJECT
DEPLOYMENTS=$DIR/deployments
KEEP=5
KEPT=$[$KEEP+1]
echo "Remove old deployments with sudo"
find "$DEPLOYMENTS" -mindepth 1 -maxdepth 1 | sort -r | tail -n +$KEPT | xargs sudo rm -rf
echo "Site started"
