#!/bin/bash

HERE=`pwd`

cp -r $HERE/public/uploads/attachments $HERE/../../uploads
echo "Attachments saved"

# docker-compose stop
docker stop studio-backend

# echo "Prune docker images and volumes"
# docker image prune -a --force && docker system prune --force && docker volume prune --force && docker network prune --force
echo "Site stopped"
